spring:
  cloud:
    gateway:
      routes:
      - id: jwt-security
        uri: http://localhost:8000/
        predicates:
        - Method=POST
        - Path=/login
        
      - id: jwt-security
        uri: http://localhost:8000/
        predicates:
        - Method=POST
        - Path=/addUser
        
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=POST
        - Path=/addDept
        filters:
        - AuthenticationFilter
        
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=GET
        - Path=/getAll
        filters:
        - AuthenticationFilter
          
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=GET
        - Path=/getDeptById/**
        filters:
        - AuthenticationFilter
        
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=DELETE
        - Path=/deleteDept/**
        filters:
        - AuthenticationFilter
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=DELETE
        - Path=/deleteStudentById/**
        filters:
        - AuthenticationFilter
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getAllStudents
        filters:
        - AuthenticationFilter
       
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getAllStudentsByDept/**
        filters:
        - AuthenticationFilter
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getAllDepartments
        filters:
        - AuthenticationFilter
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getStudentsById/**
        filters:
        - AuthenticationFilter
       
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=POST
        - Path=/addStudent
        filters:
        - AuthenticationFilter
        