spring:
 cloud:
   gateway:
     routes:
       - id: department-service
         uri: lb://department-service
         predicates:
           - Path=/getAll
         filters:
           - AuthenticationFilter
           
       - id: department-service
         uri: lb://department-service
         predicates:
           - Path=/getDeptById/**
         filters:
           - AuthenticationFilter 
       
       - id: department-service
         uri: lb://department-service
         predicates:
           - Path=/addDept
         filters:
           - AuthenticationFilter  
        
       
       - id: department-service
         uri: lb://department-service
         predicates:
           - Path=/deleteDept/**
         filters:
           - AuthenticationFilter  
           
           
       - id: student-service
         uri: lb://student-service
         predicates:
           - Path=/getStudentsById/**
         filters:
           - AuthenticationFilter
           
           
       - id: student-service
         uri: lb://student-service
         predicates:
           - Path=/getAllDepartments
         filters:
           - AuthenticationFilter
           
           
       - id: student-service
         uri: lb://student-service
         predicates:
           - Path=/getAllStudents
         filters:
           - AuthenticationFilter
           
           
       - id: student-service
         uri: lb://student-service
         predicates:
           - Path=/getAllStudentsByDept/**
         filters:
           - AuthenticationFilter
        
       - id: student-service
         uri: lb://student-service
         predicates:
           - Path=/addStudent
         filters:
           - AuthenticationFilter
        
       - id: student-service
         uri: lb://student-service
         predicates:
           - Path=/deleteStudentById/**
         filters:
           - AuthenticationFilter
       
           
    
