spring:
  cloud:
    gateway:
      routes:
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=POST
        - Path=/addDept
        
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=GET
        - Path=/getAll
          
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=GET
        - Path=/getDeptById/**
        
      - id: department-service
        uri: http://localhost:8100/
        predicates:
        - Method=DELETE
        - Path=/deleteDept/**
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=DELETE
        - Path=/deleteStudentById/**
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getAllStudents
       
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getAllStudentsByDept/**
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getAllDepartments
        
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=GET
        - Path=/getStudentsById/**
       
      - id: student-service
        uri: http://localhost:8200/
        predicates:
        - Method=POST
        - Path=/addStudent
        
        